### ISSUE TITLE
Socket.id not being generated on subsequent connections after socket.dispose() is called

### ISSUE THREAD

**Issue by arbaker2** [rikulo/socket.io-client-dart#118]
Having an issue on the flutter side where I am able to join the chatroom fine on my first attempt, but after leaving the chatroom (which calls socket.dispose()) and rejoining there is no socket.id being generated. Any thoughts as to what could be causing this?

**Comment by arbaker2** [comment]
looks like this may also be an issue on socket.io-client-java. https://github.com/socketio/socket.io-client-java/issues/325

**Comment by pA1nD** [comment]
I'm having a similar issue.

I'm using flutter and initializing (`io.io()`) in a view like follows:

```
class _VideoCallState extends State<VideoCall> {

  io.Socket socket;

  @override
  void initState() {
    super.initState();

    socket = io.io(socketsAddress, <String, dynamic>{
      'transports': ['websocket']
    });

    socket.emit('patient ready', widget.appointmentId);
    ...
  }
```

And I'm cleaning it up like the following:

```
  @override
  void dispose() {
    if (socket != null) {
      socket.dispose();
      socket.clearListeners();
    }

    ...

    super.dispose();
  }
```


calling `socket.dispos()` causes the websocket to correctly disconnect from the socket server. 
BUT once I enter the page again, which executes `initState`, there is no new connection established.

Is that expected behaviour?

**Comment by pA1nD** [comment]
I assume that it has nothing todo with the issue you linked.
I would guess you rather have no socket.id simply because you are not connected to the server.

Rather, you are relying to initiate your socket again calling `io.io()` again?

For me that only works the first time. Subsequent calls to io.io do **NOT** reconnect the scoket once it has been disconnected. This seems to be a bug for me.

The following fix worked:
```
  @override
  void initState() {
    super.initState();


    socket = io.io(socketsAddress, <String, dynamic>{
      'transports': ['websocket'],
      'autoConnect': false
    });
    // Manual connection required here. Otherwise socket will not reconnect.
    socket.connect();

    ...

}
```

**Comment by jumperchen** [comment]
From the implementation here - https://github.com/rikulo/socket.io-client-dart/blob/master/lib/socket_io_client.dart#L51-L55
It looks like the behavior is expected when `io.io()` was invoked at the second time, the `Manager` object is reused from the `cache` without auto-connecting, which the auto-connecting is invoked in the constructor of `Manager` object.
