### ISSUE TITLE
Socket is not working when app is closed or not running. 

### ISSUE THREAD

**Issue by PrabhansuTiw** [rikulo/socket.io-client-dart#227]
I have a system where I am receiving a chat request. It is working perfectly when app is running or in background but when app is closed then I am not able to receive chat request. Please suggest me what can I do for this.

**Comment by molayab** [comment]
Normally on mobile devices the OS closes sockets and other stuff in order to maximize the battery duration. On iOS the system gives around 5min to the app before puts it into suspended mode (if your are setting some background mode). After so, the system will call based on some AI-based pattern logic that give you some time to perform limited tasks on background. It doesn't work like desktop when the app becomes to background. I recommend you if this is your case, to use some fallback push-based notification in order to notify when the client is disconnected or on a background/suspended state. When foreground you can use all the socket advantages, but some workaround should be addressed on background just for mobile devices _(primary iOS)_.

**Comment by loidoan** [comment]
I also had this problem. Is there a better way to run realtime to update the location?

**Comment by thorizer** [comment]
@molayab  will these android permissions fixes this on android ? 
<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
<uses-permission android:name="android.permission.WAKE_LOCK" />
<uses-permission android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS"/>
